[project]
name = "neural-swipe-typing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gdown==5.2.0",
    "lightning==2.2.4",
    "numpy==1.26.4",
    "pandas==2.1.3",
    "requests==2.31.0",
    "torch==2.1.2",
    "tqdm==4.66.3",
]
