model_name: v3_nearest_and_traj_transformer_bigger
grid_name: qwerty_english
transform_name: traj_feats_and_nearest_key
use_time: false
use_velocity: true
use_acceleration: true
uniform_noise_range: 3
learning_rate: 0.0002
weight_decay: 0.0001
label_smoothing: 0.2
train_batch_size: 96
val_batch_size: 192
max_epochs: 300
random_seed: 42
lr_scheduler_patience: 8
lr_scheduler_factor: 0.5
gradient_clip_val: 0.5
early_stopping_patience: 15
early_stopping_monitor: val_loss
early_stopping_mode: min
checkpoint_save_top_k: 3
checkpoint_monitor: val_loss
checkpoint_mode: min
num_workers: 2
persistent_workers: true
batch_first: false
log_every_n_steps: 25
val_check_interval: 50
enable_progress_bar: true
data_root: data
train_file: raw_converted_english_swipes_train.jsonl
val_file: raw_converted_english_swipes_val.jsonl
vocab_file: data_preprocessed/english_vocab.txt
grid_file: data_preprocessed/gridname_to_grid.json
train_total: 37688
val_total: 8076
log_dir: lightning_logs/
log_name: aggressive_training
checkpoint_dir: checkpoints_english/
checkpoint_filename: english-{epoch:02d}-{val_loss:.3f}-{val_word_acc:.3f}
vocab_size: 30
criterion_ignore_index: -100
