criterion_ignore_index: 65
label_smoothing: 0.045
max_word_len: 30
model_name: v3_weighted_and_traj_transformer_bigger
n_coord_feats: 6
n_keys: 29
num_classes: 65
optim_kwargs:
  lr: 0.0001
  weight_decay: 0
train_batch_size: 256
vocab_size: 67
