criterion_ignore_index: 30
label_smoothing: 0.045
max_word_len: 30
model_name: v3_weighted_and_traj_transformer_bigger
n_coord_feats: 6
n_keys: 29
num_classes: 30
optim_kwargs:
  lr: 0.00015000000000000001
  weight_decay: 0
train_batch_size: 384
vocab_size: 32
